# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08fce221bd5da72fea305abaeaff10de6834bacb816c29c59a0f7d8f4e583a685ba6732984231105ea3ee347964e64ae5696d34d650835f4e54cf4a263382926

test:
  secret_key_base: 368f8043e3c3718d211e1da5af02c1441d070b7f988176d037ddf8ad7f6892e84a9ac46c85fbbf11bda3b38175364eec04d2856bcd20ddcdf161b2b614d2f5dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
